geotiff_dir: ${DATA_DIR}/results/TentNetFA/model_beta2.0/2026-04/tiffs
boundaries: gaza_boundaries/GazaStrip_MunicipalBoundaries.shp
prewar_gaza: ${DATA_DIR}/data/prewar_gaza_std.tif
json_folder: ${DATA_DIR}/results/TentNetFA/model_beta2.0/2026-04/jsons
hdf5_folder: ${DATA_DIR}/results/TentNetFA/model_beta2.0/2026-04/hdf5_files
artifact_dir: runs
loading:
  files:
    - "gaza_city"
    - "tel_sultan"
    - "rafah"
    - "beit_hanoun"
processing:
  individual: true
  prediction_only: true
  step: 0.0005
  max_workers: 8
  quality_thresholds:
    start_threshold: 0.2
    max_missing_end: 1.0
    min_valid_fraction: 0.9
  complete:
    - deir_el_balah_20250315_121122_ssc10_u0002_visual_clip_file_format.tif
    - netzarim_corridor_gaza_city_beit_lahiya_20250331_121449_ssc10_u0001_visual_clip.tif
    - deir_el_balah_and_nuseirat_20250326_054752_ssc2_u0002_visual_clip_file_format.tif
    - khan_yunis_20250315_065509_ssc13_u0001_visual_file_format.tif
    - gaza_city_and_jabalia_20250319_121502_ssc8_u0001_visual_clip_file_format.tif
    - deir_el_balah_20250330_121424_ssc7_u0001_visual_clip.tif
    - kerem_shalom_crossing_abasan_al_kabira_20260130_055039_ssc1_u0003_visual.tif
    - rafah_abasan_al_kabira_20260117_061143_ssc1_u0001_visual_clip.tif
rebalancing:
  inp: "train_data_labelling.h5"
  out: "train_data_labelling_balanced.h5"
  rng_seed: 42
training:
  checkpoint: runs/20260418_101249/best_model.pth
  device: cuda
  epochs: 10000
  batch_size: 64
  learning_rate: 0.001
  training_frac: 0.8
  validation_frac: 0.19
  memory: True
  model_kwargs:
    kernel_size: 3
