geotiff_dir: /data/projects/gazatents/results_karim/2026-02/tiffs
boundaries: gaza_boundaries/GazaStrip_MunicipalBoundaries.shp
prewar_gaza:  /data/projects/gazatents/results_karim/2026-02/prewar_gaza.tif
hdf5_folder: /data/projects/gazatents/results_karim/2026-02/hdf5_files_normalized
json_folder: /data/projects/gazatents/results_karim/2026-02/json_files
loading:
  files:
    - deir_el_balah_nuseirat_gaza_city_20260220_122923_ssc10_u0002_visual_clip.tif
    #- gaza_city_jabalia_beit_hanoun_20260220_123000_ssc10_u0001_visual_clip.tif
    #- gaza_city_jabalia_beit_lahiya_20260220_122923_ssc10_u0001_visual_clip.tif
    #- kerem_shalom_crossing_al_nasr_20260220_055911_ssc1_u0001_visual_clip.tif
    #- khan_yunis_al_maghazi_bureij_20260220_123000_ssc10_u0002_visual_clip.tif
    #- khan_yunis_al_mawasi_deir_el_balah_20260220_122923_ssc10_u0003_visual_clip.tif
    #- tel_al_sultan_20260220_122923_ssc10_u0004_visual_clip.tif
    #- rafah_rafah_crossing_khan_yunis_20260220_123000_ssc10_u0003_visual_clip.tif
processing:
  individual: true
  prediction_only: true
  step: 0.0005
  normalize:  # These values are directly taken from a well-performing image (deir_el_balah_nuseirat_gaza_city_20260220_122923_ssc10_u0002_visual_clip)
    enable: true
    mean: 26.0
    std: 37.5
  quality_thresholds:
    start_threshold: 0.2
    max_missing_end: 0.2
    min_valid_fraction: 0.9
prediction:
  save_bounds: true
  input_folder: /data/projects/gazatents/results_karim/2026-02/hdf5_files_normalized
  output_folder: /data/projects/gazatents/results_karim/2026-02/json_files_normalized
  model: /data/projects/gazatents/models/v1.0.pth
  batch_size: 8
  num_workers: 4  # Optional sampling configuration
  sample:
    enable: false        # set to false to run on all tiles
    size: 200           # number of random tiles to predict
    seed: 5            # optional random seed for reproducibility
  selection:
    method: nms
    agreement: false
    threshold: 0.05
    min_area: 5
    min_distance_m: 3.0
    crop_pixels: 16  # Set to radius of total receptive field
  validation_tifs: false # ideally set to false if sampling is false













































